-- Chat global da plataforma (mensagens visíveis para todos os usuários)

create table if not exists public.global_chat_messages (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0 and char_length(content) <= 2000),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_global_chat_messages_created_at
  on public.global_chat_messages (created_at desc);

create index if not exists idx_global_chat_messages_profile_id
  on public.global_chat_messages (profile_id);

alter table public.global_chat_messages enable row level security;

drop policy if exists "global_chat_messages_read_write_public" on public.global_chat_messages;
create policy "global_chat_messages_read_write_public"
on public.global_chat_messages
for all
to anon, authenticated
using (true)
with check (true);

-- Realtime (habilite também em Database > Replication no Supabase, se necessário)
alter table public.global_chat_messages replica identity full;

do $$
begin
  if exists (
    select 1 from pg_publication where pubname = 'supabase_realtime'
  ) then
    alter publication supabase_realtime add table public.global_chat_messages;
  end if;
exception
  when duplicate_object then null;
end $$;
