alter table public.profiles
  add column if not exists role text not null default 'aluno' check (role in ('aluno', 'tutor', 'aluno_tutor')),
  add column if not exists phone_whatsapp text not null default '',
  add column if not exists trial_started_at timestamptz,
  add column if not exists trial_ends_at timestamptz;

update public.profiles
set
  trial_started_at = coalesce(trial_started_at, created_at),
  trial_ends_at = coalesce(trial_ends_at, created_at + interval '7 days'),
  phone_whatsapp = coalesce(nullif(phone_whatsapp, ''), phone),
  role = coalesce(role, 'aluno');

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  price_cents integer not null check (price_cents >= 0),
  billing_cycle text not null check (billing_cycle in ('monthly', 'quarterly', 'yearly')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  plan_id bigint not null references public.plans(id) on delete restrict,
  status text not null default 'trialing' check (status in ('trialing', 'active', 'past_due', 'canceled')),
  starts_at timestamptz not null default timezone('utc', now()),
  ends_at timestamptz,
  trial_ends_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('pix', 'credito', 'debito')),
  provider text,
  last4 text,
  pix_key text,
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  subscription_id bigint references public.subscriptions(id) on delete set null,
  amount_cents integer not null check (amount_cents >= 0),
  status text not null default 'pending' check (status in ('pending', 'paid', 'failed')),
  method_type text not null check (method_type in ('pix', 'credito', 'debito')),
  paid_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  student_profile_id uuid not null references public.profiles(id) on delete cascade,
  tutor_profile_id uuid not null references public.profiles(id) on delete cascade,
  skill_id bigint not null references public.skills(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'scheduled', 'completed', 'declined')),
  scheduled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (student_profile_id <> tutor_profile_id)
);

create index if not exists idx_subscriptions_profile on public.subscriptions(profile_id);
create index if not exists idx_payment_methods_profile on public.payment_methods(profile_id);
create index if not exists idx_payments_profile on public.payments(profile_id);
create index if not exists idx_service_requests_student on public.service_requests(student_profile_id);
create index if not exists idx_service_requests_tutor on public.service_requests(tutor_profile_id);

drop trigger if exists trg_subscriptions_updated_at on public.subscriptions;
create trigger trg_subscriptions_updated_at
before update on public.subscriptions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_payment_methods_updated_at on public.payment_methods;
create trigger trg_payment_methods_updated_at
before update on public.payment_methods
for each row
execute function public.set_updated_at();

drop trigger if exists trg_service_requests_updated_at on public.service_requests;
create trigger trg_service_requests_updated_at
before update on public.service_requests
for each row
execute function public.set_updated_at();

alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.payment_methods enable row level security;
alter table public.payments enable row level security;
alter table public.service_requests enable row level security;

drop policy if exists "plans_read_write_public" on public.plans;
create policy "plans_read_write_public" on public.plans
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "subscriptions_read_write_public" on public.subscriptions;
create policy "subscriptions_read_write_public" on public.subscriptions
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "payment_methods_read_write_public" on public.payment_methods;
create policy "payment_methods_read_write_public" on public.payment_methods
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "payments_read_write_public" on public.payments;
create policy "payments_read_write_public" on public.payments
for all to anon, authenticated
using (true)
with check (true);

drop policy if exists "service_requests_read_write_public" on public.service_requests;
create policy "service_requests_read_write_public" on public.service_requests
for all to anon, authenticated
using (true)
with check (true);

insert into public.plans (name, description, price_cents, billing_cycle, is_active)
values
  ('Teste Gratuito', 'Acesso inicial para explorar a plataforma por 7 dias.', 0, 'monthly', true),
  ('Aluno Mensal', 'Plano para alunos com acesso completo a solicitacoes.', 2990, 'monthly', true),
  ('Tutor Pro', 'Plano para tutores com destaque e mais conversoes.', 4990, 'monthly', true)
on conflict do nothing;

update public.profiles
set role = case
    when name ilike '%Rafael%' or name ilike '%Mayane%' then 'aluno_tutor'
    when name ilike '%Johne%' or name ilike '%Antonieta%' then 'tutor'
    else 'aluno'
  end;

insert into public.subscriptions (profile_id, plan_id, status, starts_at, trial_ends_at)
select p.id, pl.id, 'trialing', timezone('utc', now()), coalesce(p.trial_ends_at, timezone('utc', now()) + interval '7 days')
from public.profiles p
cross join lateral (
  select id from public.plans where name = 'Teste Gratuito' limit 1
) pl
where not exists (
  select 1 from public.subscriptions s where s.profile_id = p.id
);
