create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  phone text not null default '',
  bio text not null default '',
  info text not null default 'Usuário não cadastrado',
  avatar text not null default 'https://picsum.photos/seed/default-avatar/200/200',
  institution text not null default '',
  period text not null default '',
  course text not null default '',
  onboarded boolean not null default false,
  skills_offer text not null default '',
  skills_seek text not null default '',
  credits integer not null default 0 check (credits >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  category text not null,
  credits integer not null default 1 check (credits > 0),
  image_url text not null default 'https://picsum.photos/seed/skill-default/400/300',
  owner_profile_id uuid not null references public.profiles(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.exchange_requests (
  id bigint generated by default as identity primary key,
  skill_id bigint not null references public.skills(id) on delete cascade,
  requester_profile_id uuid not null references public.profiles(id) on delete cascade,
  provider_profile_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (requester_profile_id <> provider_profile_id)
);

create table if not exists public.credit_transactions (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  kind text not null check (kind in ('onboarding_bonus', 'exchange_spent', 'exchange_earned')),
  reference_exchange_id bigint references public.exchange_requests(id) on delete set null,
  note text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_skills_owner on public.skills(owner_profile_id);
create index if not exists idx_exchange_requests_requester on public.exchange_requests(requester_profile_id);
create index if not exists idx_exchange_requests_provider on public.exchange_requests(provider_profile_id);
create index if not exists idx_credit_transactions_profile on public.credit_transactions(profile_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

drop trigger if exists trg_exchange_requests_updated_at on public.exchange_requests;
create trigger trg_exchange_requests_updated_at
before update on public.exchange_requests
for each row
execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.skills enable row level security;
alter table public.exchange_requests enable row level security;
alter table public.credit_transactions enable row level security;

drop policy if exists "profiles_read_write_public" on public.profiles;
create policy "profiles_read_write_public"
on public.profiles
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "skills_read_write_public" on public.skills;
create policy "skills_read_write_public"
on public.skills
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "exchange_requests_read_write_public" on public.exchange_requests;
create policy "exchange_requests_read_write_public"
on public.exchange_requests
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "credit_transactions_read_write_public" on public.credit_transactions;
create policy "credit_transactions_read_write_public"
on public.credit_transactions
for all
to anon, authenticated
using (true)
with check (true);

insert into public.profiles (id, name, email, phone, info, bio, avatar, institution, period, course, onboarded, credits)
values
  ('11111111-1111-1111-1111-111111111111', 'Rafael Oliveira', 'rafael.o@uemasul.edu.br', '(99) 98888-1111', 'Administração - 8º Período (Uemasul)', 'Estudante de Administração focado em processos e tecnologia. Adoro aplicar ferramentas digitais para otimizar a gestão.', 'https://picsum.photos/seed/p-rafael/200/200', 'Uemasul', '8', 'Administração', true, 3),
  ('22222222-2222-2222-2222-222222222222', 'Mayane Matos', 'mayane.m@uemasul.edu.br', '(99) 98888-2222', 'Administração - 8º Período (Uemasul)', 'Futura administradora apaixonada por oratória e liderança. Acredito que uma boa comunicação é a base de qualquer gestão de sucesso.', 'https://picsum.photos/seed/p-mayane/200/200', 'Uemasul', '8', 'Administração', true, 2),
  ('33333333-3333-3333-3333-333333333333', 'Johne Menezes', 'johne.m@uemasul.edu.br', '(99) 98888-3333', 'Administração - 8º Período (Uemasul)', 'Focado em marketing e estratégia empresarial. Estudante de Administração na Uemasul buscando inovar no mercado regional.', 'https://picsum.photos/seed/p-johne/200/200', 'Uemasul', '8', 'Administração', true, 1),
  ('44444444-4444-4444-4444-444444444444', 'Antonieta Barreto', 'antonieta.barreto@uemasul.edu.br', '(99) 99876-5432', 'Administração - 8º Período (Uemasul)', 'Estudante de Administração na Uemasul, apaixonada por lógica, gestão e troca de conhecimentos.', 'https://picsum.photos/seed/p-antonieta/200/200', 'Uemasul', '8', 'Administração', true, 2)
on conflict (id) do nothing;

insert into public.skills (title, description, category, credits, image_url, owner_profile_id)
values
  ('Tecnologia da informação', 'Mentoria prática de TI aplicada à gestão.', 'Tecnologia', 1, 'https://picsum.photos/seed/tech-skill/400/300', '11111111-1111-1111-1111-111111111111'),
  ('Oratória', 'Técnicas de fala em público para apresentações acadêmicas.', 'Comunicação', 1, 'https://picsum.photos/seed/speech-skill/400/300', '22222222-2222-2222-2222-222222222222'),
  ('Marketing Digital', 'Planejamento e execução de campanhas digitais.', 'Marketing', 1, 'https://picsum.photos/seed/market-skill/400/300', '33333333-3333-3333-3333-333333333333'),
  ('Cálculo', 'Revisão aplicada a problemas de negócios e administração.', 'Exatas', 1, 'https://picsum.photos/seed/math-skill/400/300', '44444444-4444-4444-4444-444444444444')
on conflict do nothing;
