create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  username text not null unique,
  password_hash text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.app_users enable row level security;

drop policy if exists "app_users_no_direct_read" on public.app_users;
create policy "app_users_no_direct_read"
on public.app_users
for select
to anon, authenticated
using (false);

drop policy if exists "app_users_no_direct_write" on public.app_users;
create policy "app_users_no_direct_write"
on public.app_users
for all
to anon, authenticated
using (false)
with check (false);

create or replace function public.authenticate_app_user(p_username text, p_password text)
returns table(profile_id uuid, username text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select au.profile_id, au.username
  from public.app_users au
  where lower(au.username) = lower(trim(p_username))
    and au.password_hash = md5(p_password)
    and au.is_active = true
  limit 1;
end;
$$;

grant execute on function public.authenticate_app_user(text, text) to anon, authenticated;

insert into public.app_users (profile_id, username, password_hash, is_active)
select
  p.id,
  p.email,
  md5('123321'),
  true
from public.profiles p
on conflict (profile_id) do update
set
  username = excluded.username,
  password_hash = excluded.password_hash,
  is_active = true;